name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Обновил до актуальной версии

      # Шаги для СЕРВЕРА
      - name: Install Server dependencies
        working-directory: ./server
        run: npm install

      # - name: Run Server tests
      #   working-directory: ./server
      #   run: npx jest --watchAll=false

      # Шаги для КЛИЕНТА (React)
      - name: Install Client dependencies
        working-directory: ./client
        run: npm install

      - name: Build Client
        working-directory: ./client
        run: npm run build

      # Финальная сборка Docker (если используешь)
      - name: Build Docker image
        run: docker build -t volunteer-tracker-server ./server
